/* AUTOGENERATED FILE, DO NOT EDIT */
#include "./common.h"

void test_ADD__immediate___1() {
#define TEST_NAME "ADD (immediate) #1"
uint8_t program[] = {72, 65};
memreg_t *mem_first = NULL;
cpu_t *cpu = cpu_new(program, sizeof(program), mem_first);
cpu_reg_write(cpu, ARM_REG_R0, 0);
cpu_reg_write(cpu, ARM_REG_R1, 0);
for (size_t i = 0; i < 1; i++) {
cpu_step(cpu);
}
uint32_t value;
value = cpu_reg_read(cpu, ARM_REG_R0); 
if (value != 0)
	printf("Register R0: expected 0, got %d\n", value);
#undef TEST_NAME
}

void test_ADD__immediate___2() {
#define TEST_NAME "ADD (immediate) #2"
uint8_t program[] = {72, 65};
memreg_t *mem_first = NULL;
cpu_t *cpu = cpu_new(program, sizeof(program), mem_first);
cpu_reg_write(cpu, ARM_REG_R0, 1);
cpu_reg_write(cpu, ARM_REG_R1, 2);
for (size_t i = 0; i < 1; i++) {
cpu_step(cpu);
}
uint32_t value;
value = cpu_reg_read(cpu, ARM_REG_R0); 
if (value != 3)
	printf("Register R0: expected 0, got %d\n", value);
#undef TEST_NAME
}

