/* AUTOGENERATED FILE, DO NOT EDIT */
#include <stdio.h>

typedef void (*test_t)();

void test_ADD__immediate___1();
void test_ADD__immediate___2();

int main() {
printf("Running tests for adc\n");
printf("  [*] ADD (immediate) #1\n");
test_ADD__immediate___1();
printf("  [*] ADD (immediate) #2\n");
test_ADD__immediate___2();
}
