#pragma once

#define ARM_REG_R0 0
#define ARM_REG_R1 1
#define ARM_REG_R2 2
#define ARM_REG_R3 3
#define ARM_REG_R4 4
#define ARM_REG_R5 5
#define ARM_REG_R6 6
#define ARM_REG_R7 7
#define ARM_REG_R8 8
#define ARM_REG_R9 9
#define ARM_REG_R10 10
#define ARM_REG_R11 11
#define ARM_REG_R12 12
#define ARM_REG_SP 13
#define ARM_REG_LR 14
#define ARM_REG_PC 15

#define ARM_EXCEPTION_RESET 1
#define ARM_EXCEPTION_NMI 2
#define ARM_EXCEPTION_HARDFAULT 3
#define ARM_EXCEPTION_MEMMANAGE 4
#define ARM_EXCEPTION_BUSFAULT 5
#define ARM_EXCEPTION_USAGEFAULT 6
#define ARM_EXCEPTION_SVC 11
#define ARM_EXCEPTION_DEBUGMONITOR 12
#define ARM_EXCEPTION_PENDSV 14
#define ARM_EXCEPTION_SYSTICK 15
