#pragma once

#define ARM_EXCEPTION_RESET 1
#define ARM_EXCEPTION_NMI 2
#define ARM_EXCEPTION_HARDFAULT 3
#define ARM_EXCEPTION_MEMMANAGE 4
#define ARM_EXCEPTION_BUSFAULT 5
#define ARM_EXCEPTION_USAGEFAULT 6
#define ARM_EXCEPTION_SVC 11
#define ARM_EXCEPTION_DEBUGMONITOR 12
#define ARM_EXCEPTION_PENDSV 14
#define ARM_EXCEPTION_SYSTICK 15

#define APSR_N 31
#define APSR_Z 30
#define APSR_C 29
#define APSR_V 28
#define APSR_Q 27
#define APSR_GE (0b1111 << 16)

#define EPSR_T 24

#define CONTROL_nPRIV 0
#define CONTROL_SPSEL 1
#define CONTROL_FPCA 2

typedef enum
{
    ARM_MODE_THREAD = 0,
    ARM_MODE_HANDLER = 1,
} arm_mode;
