#pragma once

#define ENABLE_LOG_GDB 0
#define ENABLE_LOG_CPU_EXCEPTIONS 0
#define ENABLE_LOG_CPU_INSTRUCTIONS 0
#define ENABLE_LOG_CPU_IT 0
#define ENABLE_LOG_SEGGER_RTT 1
#define ENABLE_LOG_SPI_FLASH 0
#define ENABLE_LOG_BMA425 0

#define ENABLE_SEGGER_RTT 1
#define ENABLE_MEASUREMENT 0

#define ABORT_ON_INVALID_MEM_ACCESS 1

#define ASSERT_EXCEPTION_REGISTERS 0

#include "user_config.h"

#if WASM
#ifdef ENABLE_SEGGER_RTT
#undef ENABLE_SEGGER_RTT
#endif
#define ENABLE_SEGGER_RTT 0
#endif
