// #define ENABLE_LOG_GDB 1
// #define ENABLE_LOG_CPU_EXCEPTIONS 1
// #define ENABLE_LOG_CPU_INSTRUCTIONS 1
// #define ENABLE_LOG_CPU_IT 1
#define ENABLE_LOG_SEGGER_RTT 1
#define ENABLE_LOG_SPI_FLASH 1
#define ENABLE_LOG_BMA425 1

#define ENABLE_SEGGER_RTT 1
// #define ENABLE_MEASUREMENT 1

#define ABORT_ON_INVALID_MEM_ACCESS 1

// #define ASSERT_EXCEPTION_REGISTERS 1
